language: c++
os:
- linux
- osx
sudo: required
group: travis_lts
git:
  depth: 1000000
env:
  global:
    - secure: led20fd/4v+u9dz16qUT32sq1L0FfSHlMztP9CzIg57LohPcIcaP9sS0CSSG4scu3s9ZbTOWwoGcrlsRzK7fJI9gEsjoTV1XQjuJUfFjv+t1B4jiVR7Q2kx4PGMoYtxfRnH2+7KD28/c8DYtM5RVSrPErV/2HESbRCxPD/IUPEfwrt+s5ysS5PKzshJnLdi1DTT5YsJ9oUIzo5epBGz4i+Y+tbLrsvw97i6NebQpNzbpO0PZwaxfkk16unlinCjddA0k3aom1mKv8IjiEETClBURlsS6AbpCaP9MbJGiyx2yfK5BzPKpCWmVFlrfIn28GNkTeadyu4m/w3vxco/sXLDZKibXWCBHLO/zkYSeHU+umLOrJw6Pxc0OW5K28em+NDtLWMRehJlsAi3cjNkhmLBsga91k3Po5CKpeTal0QEv/+dtCxOQC3QOwcb/JMEj8oISFUK+WEamVjYbAo6l1zceYINSMBGrJ/7Hoxsz39muLm+7swF1F9RtcLfIk8Jd4GdMaKMooSKQTkEpM344FWNt4+kUqDlUeJtUZ551nNVjcMc9wOBVwSdsnAEMCPttb/6a1ricagZMtt5YBeKYjIXsLukzV4/lKAiGX3KDhVBF4qgN0YBtBB9TLD/5WtvHDI661VWhayh087XIBCytuVZD1CSfrUs/kYHIv3ehiDo=
    - apiuser=joerghall
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl readline ; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -v ${TRAVIS_BUILD_DIR}:/root/pypack
  -e apipwd -e apiuser -e TRAVIS_BRANCH --rm -t jhhj/cbt-pypack-centos7:1 /bin/bash
  -c "mkdir /root/pypack/build && cd /root/pypack/build && export PATH=/opt/rh/devtoolset-6/root/usr/bin:$PATH
  && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --target publish_python"
  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir ${TRAVIS_BUILD_DIR}/build && cd
  ${TRAVIS_BUILD_DIR}/build && cmake .. && cmake --build . --target publish_python
  ; fi
