language: c++
os:
- linux
- osx
sudo: required

git:
  depth: 1000000
env:
  global:
  - secure: "gFAgMSJEjy495VUpJr9c1TekDVoH11vcMvCHAkPeEaLkN8j7W+1vQqMYsMdxP88TTwPR3cl17mauVOpTnRSFpfjOb3TqbjRp1fmjyj1DOhXrR4sWkSN6nLdPTgrXFCgDZHKbxoVtkNXV16ZcVMPFNBdScmo2osl2PPQfoWpoV+Xf04/El/ISRKt7lA2hsDoTNxPqHmEDBcaHO80VnCYPAs4ucybiizDrhK5uiGjz2MGVEj9AuWDpZDK1e4BJYF9z9AJHn6Hek/L1+jM7BqHHKSIouarJkaZcjvHZ6v0DxIxTevsmpXCmuEMa5UbUaXGkgq8T2rJfVle2bG0Tgz+mw74F8NN6sJaawu0/TUY2NlkU5uwkqZzBIwZ4tKHGQ6uGJ/2+HhqqkmJdjfbkweRfwTpZQPv1KKODq8AzXCsFF8hXn5aJOyPeAo92PApDUaGY5HPMTEcwl36Bg6rVoGMyWa+j/pQ0gnMiqVZpaSzqAWqI9hEXk4ZSurQv+kgq1jXs4G2loOYtYIntNQXnmWR/oAtoXEXWS3aZjMQoy1f7M31Wr3hWyhkRn3eJai+g5eVwu/kcsvxJCBN0uE00rqWuC82ia1ZLqkhopSp9mtkpf4a4nV3ITnc6Fwb5qf/EjS95vBmelqNgGT6jF2AoNWqM9xBf6SlV3ghe0AHMr5ssZgg="
  - apiuser=joerghall

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t centos7_pypack -f ${TRAVIS_BUILD_DIR}/docker/centos.docker docker ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -v ${TRAVIS_BUILD_DIR}:/root/pypack -e apikey -e apiuser -e TRAVIS_BRANCH
  --rm -t centos7_buildpy /bin/bash -c "mkdir /root/pypack/build
    && cd /root/pypack/build
    && cmake -DCMAKE_C_COMPILER=/opt/rh/devtoolset-6/root/usr/bin/gcc -DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-6/root/usr/bin/g++ -DCMAKE_BUILD_TYPE=Release ..
    && cmake --build . --target publish_package" ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir ${TRAVIS_BUILD_DIR}/build
    && cd ${TRAVIS_BUILD_DIR}/build && cmake ..
    && cmake --build . --target publish_package ; fi
