language: c++
os:
- linux
- osx
sudo: required
group: travis_lts
git:
  depth: 1000000
env:
  global:
    - secure: "GxLN7GlM0qsioMwzWWuXST/x972Lod3KLJVnu/un+T6+P5lKArFuikLmde5bw9fnlQri/SjKHjPNf1McT2Yug8QzlefmKdEHWPJ1iWteIAt7BprZume0tFj50E0EKvWvZhYMOIokve6m85+yjABRnHpYMK8s9aj0Q8ZtV7ybfbAOaoW0gCrF7VaMtCO0Bwcy7IlR6z0CFefFXi8C4Yhl9tWxAb8VZBatSEpXiyLgc1iVuZz4E+ohEJkz5ELWaJetfJaziAKIYlnUpEefA3kgPUmYArqI2i7NyiJuiRdpSWtkLiiMZDufrlOV8k0znJwaGDHIus3zK0Q2vr19Hk4isv6g7pq+x9hLuILYOS2rkcvrYsVwMfv1kQk0CP2S8tTF5mH/+uQDU8XKVccdB71ekqs1Z+4xpxNAJ5/i1rYX2FH8MBfC4GW7YHhizY1/3bokfi53o/kjSpAmeRa//TPvtF6U1SJdyYBU28BJ0qbs00itao/OQPhgtp0mS9kPySrDrBcy7hnL3/QMLeGnbxe9XPZCL9+UiRK3Fi3oQTwaT5lUOTMiatHdrtyKIBJOsTjJCPduCo/DPsG7HeB6ILC4addIKYJN0xwtr98i33eZnV9GahnX2CxJudc4b4c8moWLYgAZvf3O7FudoyPXjNUsnNLH+hzeNUE3Lr7t+qeKNcE="
    - apiuser=joerghall
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl readline ; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -v ${TRAVIS_BUILD_DIR}:/root/pypack
  -e apipwd -e apiuser -e TRAVIS_BRANCH --rm -t jhhj/cbt-pypack-centos7:1 /bin/bash
  -c "mkdir /root/pypack/build && cd /root/pypack/build && export PATH=/opt/rh/devtoolset-6/root/usr/bin:$PATH
  && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --target publish_python"
  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir ${TRAVIS_BUILD_DIR}/build && cd
  ${TRAVIS_BUILD_DIR}/build && cmake .. && cmake --build . --target publish_python
  ; fi
